### ISSUE TITLE
feat: exiting bed

### ISSUE THREAD

**Issue by piprett** [Arbee4ever/Bedventory#1]
It would be nice if it was possible to exit the bed like normal. With this mod, if you press ESC the inventory dissapears, before quickly reappearing.

Very nice mod by the way! It is a small change to the game, but it helps a lot!

**edit:**
After reading the code i discovered that i could actually exit the bed, just not thru the normal keybind

**Comment by Arbee4ever** [comment]
I could add a button that does that to the Screen...

**Comment by piprett** [comment]
> I could add a button that does that to the Screen...

I was more meaning that when pressing escape i want to go out of the bed.

**Comment by Arbee4ever** [comment]
I actually already added this, due to it causing some people to not be able to leave the bed... In the newest Version you should be able to click the newly added button or press esc or e to leave the inventory and bed
