### ISSUE TITLE
Soooo.... Fabric version?

### ISSUE THREAD

**Issue by Scarlaid** [Arbee4ever/Bedventory#2]
This is actually a good idea of a mod since
###### who even talk while sleeping

I would love to see a Fabric version, because I don't use Quilt 💀

**Comment by Arbee4ever** [comment]
You can use any Fabric Mod with Quilt... Check out [Quilt's FAQ](https://quiltmc.org/en/about/faq/) to find out how to

**Comment by Scarlaid** [comment]
> You can use any Fabric Mod with Quilt... Check out [Quilt's FAQ](https://quiltmc.org/en/about/faq/) to find out how to

I did try before asking this, and the mod did not load nor displayed in Mod Menu
Also no, I don't plan to change to Quilt because of some mods somehow don't like Quilt lol
![image](https://user-images.githubusercontent.com/90851437/201967716-962b2e45-969f-4bae-b0cc-6423eff19e0d.png)

**Comment by Scarlaid** [comment]
Nevermind, I was so wrong, sorry......

![image](https://user-images.githubusercontent.com/90851437/201970146-04fe174d-f640-4cb8-9161-2386721c7a23.png)
